#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Fri Oct 12 01:54:18 2018

@author: stephaniearaki
"""

#Question 1
import pandas as pd
wages=pd.read_csv('wages.csv')
n = 5
wages.head(n) 


#Question 2
import pandas as pd
iris=pd.read_csv('iris.csv')
iris.shape

#print last 2 rows and last 2 columns to terminal
iris.iloc[148:150 , 3:5]

#get number of observations for each species
species=iris.iloc[:,4:]
species.shape
specieslist=iris['Species'].tolist()
from collections import Counter
print 'Number of observations for each species:'
Counter(specieslist)

#get rows with Sepal.Width>3.5
bigsepal=iris.loc[iris['Sepal.Width']>3.5]
print 'Sepal Width over 3.5:'
print bigsepal

#write data for Species setosa to comma-delimited file
setosa=iris.loc[iris['Species']=='setosa']
setosa.to_csv('setosa.csv')

#calculate mean, min and max of Petal.Length for virginica
virginica=iris[iris['Species']=='virginica']
minPetal=min(virginica['Petal.Length'])
print 'minimum Petal Length:'
minPetal
maxPetal=max(virginica['Petal.Length'])
print 'maximum Petal Length:'
maxPetal
sumPetal=sum(virginica['Petal.Length'])
virginica.shape
meanPetal=(sumPetal/50)
print 'mean Petal Length:'
meanPetal
